Remove publishable key (#19)
Fix git hooks for publishable key check

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -16,23 +16,24 @@ github_deps=$(grep -E "https://github.com" package.json)
 
 # If github dependencies are found, exit with an error message
 if [ "$github_deps" ]; then
- echo "$check_error: Github dependencies found in package.json: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
- exit 1
+  echo "$check_error: Github dependencies found in package.json: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
+  exit 1
 fi
 
-# Check if publishable key is set in App.tsx
-# Get the length of the PUBLISHABLE_KEY constant
-LENGTH=$(grep -o 'PUBLISHABLE_KEY = .*' src/App.tsx | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')
+if grep -q "'.\{86\}'" "src/App.tsx"; then
+  echo "$check_error: PUBLISHABLE_KEY is set"
+  exit 1
+fi
 
-if [ $LENGTH -eq 86 ]; then
- echo "$check_error: PUBLISHABLE_KEY is set"
- exit 1
+if ! grep -q "Paste_your_publishable_key_here" "src/App.tsx"; then
+  echo "$check_error: PUBLISHABLE_KEY is probably set ('Paste_your_publishable_key_here' not found)"
+  exit 1
 fi
 
 xcode_project_config_path="ios/QuickstartReactNative.xcodeproj/project.pbxproj"
 
 # Check if the xcodeproj command line tool is installed
-if ! type "xcodeproj" > /dev/null; then
+if ! type "xcodeproj" >/dev/null; then
   echo "$check_error: The xcodeproj command line tool is not installed. Unable to check if the development team is set up."
 else
   # Check if the project file exists
