Enable back hooks. Update lock.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -11,23 +11,23 @@ if [ "$local_deps" ]; then
   exit 1
 fi
 
-## Check if there are any Github dependencies in the package.json file
-#github_deps=$(grep -E "https://github.com" package.json)
-#
-## If github dependencies are found, exit with an error message
-#if [ "$github_deps" ]; then
-#  echo "$check_error: Github dependencies found in package.json: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
-#  exit 1
-#fi
-#
-## Check if publishable key is set in App.tsx
-## Get the length of the PUBLISHABLE_KEY constant
-#LENGTH=$(grep -o 'PUBLISHABLE_KEY = .*' src/App.tsx | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')
-#
-#if [ $LENGTH -eq 86 ]; then
-#  echo "$check_error: PUBLISHABLE_KEY is set"
-#  exit 1
-#fi
+# Check if there are any Github dependencies in the package.json file
+github_deps=$(grep -E "https://github.com" package.json)
+
+# If github dependencies are found, exit with an error message
+if [ "$github_deps" ]; then
+ echo "$check_error: Github dependencies found in package.json: \n\n $github_deps \n\n Push blocked to prevent committing Github dependencies."
+ exit 1
+fi
+
+# Check if publishable key is set in App.tsx
+# Get the length of the PUBLISHABLE_KEY constant
+LENGTH=$(grep -o 'PUBLISHABLE_KEY = .*' src/App.tsx | cut -d'"' -f2 | wc -c | awk '{$1=$1-1}1')
+
+if [ $LENGTH -eq 86 ]; then
+ echo "$check_error: PUBLISHABLE_KEY is set"
+ exit 1
+fi
 
 xcode_project_config_path="ios/QuickstartReactNative.xcodeproj/project.pbxproj"
 
